**240840116011**

**Practical 2**

**Aim: Perform data inspection, cleaning, handling missing values, duplicate removal, and data transformation using Pandas.**

**Step 1: Import Pandas**

In [1]:
# Import the Pandas library
# Pandas is used to work with tables (DataFrames)
import pandas as pd

**Step 2:Create Sample Data**

In [2]:
# Create a dictionary to store student data
# Each key (ID, Name, Age, etc.) becomes a column
# Each list becomes the values of that column
data = {
    "ID": [101,102,103,104,104,105,106,107],
    "Name": ["Rahul", "Priya", "Amit",None, "Karan", "Riya", "Aman","Ajay"],
    "Age": [20, 21, None, 20, 20, 22, 23, 28],
    "City": ["Surat", "Navsari", "Valsad", "Surat", "Gandhinagar", "Bharuch","Navsari","Ahemdabad"],
    "Marks": [85, None, 78, 88, 88, 81, 90, 91]
}

**Step 3: Create a Dataframe**

In [3]:
# Convert the dictionary into a Pandas DataFrame
# A DataFrame represents data in rows and columns
df = pd.DataFrame(data)

# Display the DataFrame
df

    ID   Name   Age         City  Marks
0  101  Rahul  20.0        Surat   85.0
1  102  Priya  21.0      Navsari    NaN
2  103   Amit   NaN       Valsad   78.0
3  104   None  20.0        Surat   88.0
4  104  Karan  20.0  Gandhinagar   88.0
5  105   Riya  22.0      Bharuch   81.0
6  106   Aman  23.0      Navsari   90.0
7  107   Ajay  28.0    Ahemdabad   91.0

**Step 4: Inspection**

Task 1: Display first five rows of dataset

In [4]:
# Display the first 5 rows of the DataFrame
df.head()

    ID   Name   Age         City  Marks
0  101  Rahul  20.0        Surat   85.0
1  102  Priya  21.0      Navsari    NaN
2  103   Amit   NaN       Valsad   78.0
3  104   None  20.0        Surat   88.0
4  104  Karan  20.0  Gandhinagar   88.0

Task 2: Display last five rows of dataset

In [5]:
# Display the last 5 rows of the DataFrame
df.tail()

    ID   Name   Age         City  Marks
3  104   None  20.0        Surat   88.0
4  104  Karan  20.0  Gandhinagar   88.0
5  105   Riya  22.0      Bharuch   81.0
6  106   Aman  23.0      Navsari   90.0
7  107   Ajay  28.0    Ahemdabad   91.0

Task 3: Display detailed info about dataset

In [6]:
# Display information about the DataFrame
# It shows columns, data types and non-empty values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

Task 4: Generate Statical info

In [7]:
# Display statistical information about numerical columns
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  85.857143
std      2.00   2.886751   4.810702
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  91.000000

Task 5:  Display dimension of dataset

In [8]:
# Display the number of rows and columns
df.shape

(8, 5)

Task 6: Display the name of all columns

In [9]:
# Display the names of all columns
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Task 7: Display the data type of each column

In [10]:
# Display the data type of each column
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

**Step 5: Check Missing Values**

In [11]:
# Check for missing values in each column
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

**Step 6: Fill Missing Marks**

In [12]:
# Replace missing Marks with the average Marks
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

# Display the updated DataFrame
df

    ID   Name   Age         City      Marks
0  101  Rahul  20.0        Surat  85.000000
1  102  Priya  21.0      Navsari  85.857143
2  103   Amit   NaN       Valsad  78.000000
3  104   None  20.0        Surat  88.000000
4  104  Karan  20.0  Gandhinagar  88.000000
5  105   Riya  22.0      Bharuch  81.000000
6  106   Aman  23.0      Navsari  90.000000
7  107   Ajay  28.0    Ahemdabad  91.000000

**Step 7: Fill Missing Age**

In [13]:
# Replace missing Age with the average Age
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Display the updated DataFrame
df

    ID   Name   Age         City      Marks
0  101  Rahul  20.0        Surat  85.000000
1  102  Priya  21.0      Navsari  85.857143
2  103   Amit  22.0       Valsad  78.000000
3  104   None  20.0        Surat  88.000000
4  104  Karan  20.0  Gandhinagar  88.000000
5  105   Riya  22.0      Bharuch  81.000000
6  106   Aman  23.0      Navsari  90.000000
7  107   Ajay  28.0    Ahemdabad  91.000000

**Step 8: Fill Missing Name**

In [14]:
# Replace missing names with the word "Unknown"
df['Name'] = df['Name'].fillna("Unknown")

# Display the updated DataFrame
df

    ID     Name   Age         City      Marks
0  101    Rahul  20.0        Surat  85.000000
1  102    Priya  21.0      Navsari  85.857143
2  103     Amit  22.0       Valsad  78.000000
3  104  Unknown  20.0        Surat  88.000000
4  104    Karan  20.0  Gandhinagar  88.000000
5  105     Riya  22.0      Bharuch  81.000000
6  106     Aman  23.0      Navsari  90.000000
7  107     Ajay  28.0    Ahemdabad  91.000000

**Step 9: Detect Duplicat Records**

Task 1: check wheather each row is duplicated

In [15]:
# Check which rows are duplicated
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

Task 2: Count total number of duplicate rows

In [16]:
# Count the total number of duplicate rows
df.duplicated().sum()

np.int64(0)

**Step 10: Remove Duplicat Records**

In [17]:
# Remove duplicate rows from the DataFrame
df = df.drop_duplicates()

# Display the DataFrame after removing duplicates
df

    ID     Name   Age         City      Marks
0  101    Rahul  20.0        Surat  85.000000
1  102    Priya  21.0      Navsari  85.857143
2  103     Amit  22.0       Valsad  78.000000
3  104  Unknown  20.0        Surat  88.000000
4  104    Karan  20.0  Gandhinagar  88.000000
5  105     Riya  22.0      Bharuch  81.000000
6  106     Aman  23.0      Navsari  90.000000
7  107     Ajay  28.0    Ahemdabad  91.000000

**Step 11: Rename Column**

In [18]:
# Rename the "Marks" column to "Score"
df.rename(columns={"Marks": "Score"}, inplace=True)

# Display the updated DataFrame
df

    ID     Name   Age         City      Score
0  101    Rahul  20.0        Surat  85.000000
1  102    Priya  21.0      Navsari  85.857143
2  103     Amit  22.0       Valsad  78.000000
3  104  Unknown  20.0        Surat  88.000000
4  104    Karan  20.0  Gandhinagar  88.000000
5  105     Riya  22.0      Bharuch  81.000000
6  106     Aman  23.0      Navsari  90.000000
7  107     Ajay  28.0    Ahemdabad  91.000000

**Step 12: Change the data type**

In [19]:
# Convert Age column from float to integer
df['Age'] = df['Age'].astype(int)

# Display the updated DataFrame
df

    ID     Name  Age         City      Score
0  101    Rahul   20        Surat  85.000000
1  102    Priya   21      Navsari  85.857143
2  103     Amit   22       Valsad  78.000000
3  104  Unknown   20        Surat  88.000000
4  104    Karan   20  Gandhinagar  88.000000
5  105     Riya   22      Bharuch  81.000000
6  106     Aman   23      Navsari  90.000000
7  107     Ajay   28    Ahemdabad  91.000000

**Step 13: Create a new column**

In [20]:
# Create a new column named "Final Score"
# Add 5 marks to each student's Score
df['Final Score'] = df['Score'] + 5

# Display the updated DataFrame
df

    ID     Name  Age         City      Score  Final Score
0  101    Rahul   20        Surat  85.000000    90.000000
1  102    Priya   21      Navsari  85.857143    90.857143
2  103     Amit   22       Valsad  78.000000    83.000000
3  104  Unknown   20        Surat  88.000000    93.000000
4  104    Karan   20  Gandhinagar  88.000000    93.000000
5  105     Riya   22      Bharuch  81.000000    86.000000
6  106     Aman   23      Navsari  90.000000    95.000000
7  107     Ajay   28    Ahemdabad  91.000000    96.000000

**Step 14: Convert text into Uppercase**

In [21]:
# Convert all Student names to uppercase
df['Name'] = df['Name'].str.upper()

# Display the updated DataFrame
df

    ID     Name  Age         City      Score  Final Score
0  101    RAHUL   20        Surat  85.000000    90.000000
1  102    PRIYA   21      Navsari  85.857143    90.857143
2  103     AMIT   22       Valsad  78.000000    83.000000
3  104  UNKNOWN   20        Surat  88.000000    93.000000
4  104    KARAN   20  Gandhinagar  88.000000    93.000000
5  105     RIYA   22      Bharuch  81.000000    86.000000
6  106     AMAN   23      Navsari  90.000000    95.000000
7  107     AJAY   28    Ahemdabad  91.000000    96.000000

**Step 15: Convert text to lowercase**

In [22]:
# Convert all city names to lowercase
df['City'] = df['City'].str.lower()

# Display the updated DataFrame
df

    ID     Name  Age         City      Score  Final Score
0  101    RAHUL   20        surat  85.000000    90.000000
1  102    PRIYA   21      navsari  85.857143    90.857143
2  103     AMIT   22       valsad  78.000000    83.000000
3  104  UNKNOWN   20        surat  88.000000    93.000000
4  104    KARAN   20  gandhinagar  88.000000    93.000000
5  105     RIYA   22      bharuch  81.000000    86.000000
6  106     AMAN   23      navsari  90.000000    95.000000
7  107     AJAY   28    ahemdabad  91.000000    96.000000

**Step 16: Remove Extra Spaces**

In [23]:
# Remove leading and trailing spaces from city names
df['City'] = df['City'].str.strip()

# Display the updated DataFrame
df

    ID     Name  Age         City      Score  Final Score
0  101    RAHUL   20        surat  85.000000    90.000000
1  102    PRIYA   21      navsari  85.857143    90.857143
2  103     AMIT   22       valsad  78.000000    83.000000
3  104  UNKNOWN   20        surat  88.000000    93.000000
4  104    KARAN   20  gandhinagar  88.000000    93.000000
5  105     RIYA   22      bharuch  81.000000    86.000000
6  106     AMAN   23      navsari  90.000000    95.000000
7  107     AJAY   28    ahemdabad  91.000000    96.000000

**Step 17: Sort the Dataset**

In [24]:
# Sort the DataFrame using the Final Score column
# Sort from highest score to lowest score
df.sort_values(by='Final Score', ascending=False)

    ID     Name  Age         City      Score  Final Score
7  107     AJAY   28    ahemdabad  91.000000    96.000000
6  106     AMAN   23      navsari  90.000000    95.000000
3  104  UNKNOWN   20        surat  88.000000    93.000000
4  104    KARAN   20  gandhinagar  88.000000    93.000000
1  102    PRIYA   21      navsari  85.857143    90.857143
0  101    RAHUL   20        surat  85.000000    90.000000
5  105     RIYA   22      bharuch  81.000000    86.000000
2  103     AMIT   22       valsad  78.000000    83.000000

**Step 18: Save the cleaned Dataset**

In [25]:
# Save the cleaned DataFrame as a new CSV file
# index=False prevents row numbers from being saved
df.to_csv("Cleaned_Students.csv",index=False)

# Display a success message
print("Dataset Saved Successfully.")

Dataset Saved Successfully.