**240840116011**

**Practical 1**

**Aim: Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas.**

**Step 1: Import pandas**

In [ ]:
# Import the Pandas library
# Pandas is used to work with tables (DataFrames)
import pandas as pd

**Step 2:Create Sample Data**

In [ ]:
# Create a dictionary to store student data
# Each key (ID, Name, Age, etc.) becomes a column
# Each list becomes the values of that column
data = {
    "ID": [1,2,3,4,5,6],
    "Name": ["Rahul", "Priya", "Amit", "Karan", "Riya", "Aman"],
    "Age": [25, 30, 35, 40, 45, 50],
    "City": ["Surat", "Navsari", "Valsad", "Surat", "Gandhinagar", "Bharuch"],
    "Marks": [90, 85, 80, 75, 70, 65]
}

**Step 3: Create a Dataframe**

In [ ]:
# Creating a dataframe named df
# Convert the dictionary into a Pandas DataFrame (table)
df = pd.DataFrame(data)

# Display the DataFrame
df

   ID   Name  Age         City  Marks
0   1  Rahul   25        Surat     90
1   2  Priya   30      Navsari     85
2   3   Amit   35       Valsad     80
3   4  Karan   40        Surat     75
4   5   Riya   45  Gandhinagar     70
5   6   Aman   50      Bharuch     65

**Step 4: Save Data As a CSV File**

In [ ]:
# Save the DataFrame as a CSV file

# index=False means do not save row numbers in the CSV file
df.to_csv("students.csv", index=False)

# Print a success message
print("CSV file created successfully")

CSV file created successfully

**Step 5: Save Data as an Excel File**

In [ ]:
# Save the DataFrame as an Excel file

# index=False means do not save row numbers in the Excel file
df.to_excel("students.xlsx", index=False)

# Print a success message
print("Excel file created successfully")

Excel file created successfully

**Step 6: Save Data as a JSON File**

In [ ]:
# Save the DataFrame as a JSON file

# orient="records" stores each row as a separate JSON object
# indent=4 adds spaces to make the JSON file easy to read
df.to_json("students.json", orient="records", indent=4)

# Print a success message
print("JSON file created successfully")

JSON file created successfully

**Step 7: Read the CSV file**

In [ ]:
# Read the CSV file into a DataFrame
df_csv = pd.read_csv("students.csv")

# Display the DataFrame
df_csv

   ID   Name  Age         City  Marks
0   1  Rahul   25        Surat     90
1   2  Priya   30      Navsari     85
2   3   Amit   35       Valsad     80
3   4  Karan   40        Surat     75
4   5   Riya   45  Gandhinagar     70
5   6   Aman   50      Bharuch     65

**Step 8: Read the Excel file**

In [ ]:
# Read the Excel file into a DataFrame
df_excel = pd.read_excel("students.xlsx")

# Display the DataFrame
df_excel

   ID   Name  Age         City  Marks
0   1  Rahul   25        Surat     90
1   2  Priya   30      Navsari     85
2   3   Amit   35       Valsad     80
3   4  Karan   40        Surat     75
4   5   Riya   45  Gandhinagar     70
5   6   Aman   50      Bharuch     65

**Step 9: Read the JSON file**

In [ ]:
# Read the JSON file into a DataFrame
df_json = pd.read_json("students.json")

# Display the DataFrame
df_json

   ID   Name  Age         City  Marks
0   1  Rahul   25        Surat     90
1   2  Priya   30      Navsari     85
2   3   Amit   35       Valsad     80
3   4  Karan   40        Surat     75
4   5   Riya   45  Gandhinagar     70
5   6   Aman   50      Bharuch     65

**Step 10: Display the first 5 records**

In [ ]:
# Show the first 5 rows of the DataFrame
df_csv.head()

   ID   Name  Age         City  Marks
0   1  Rahul   25        Surat     90
1   2  Priya   30      Navsari     85
2   3   Amit   35       Valsad     80
3   4  Karan   40        Surat     75
4   5   Riya   45  Gandhinagar     70

**Step 11: Display the Last 5 Records**

In [ ]:
# Show the last 5 rows of the DataFrame
df_csv.tail()

   ID   Name  Age         City  Marks
1   2  Priya   30      Navsari     85
2   3   Amit   35       Valsad     80
3   4  Karan   40        Surat     75
4   5   Riya   45  Gandhinagar     70
5   6   Aman   50      Bharuch     65

**Step 12: Diplay Dataset Information**

In [ ]:
# Display information about the DataFrame
# Shows column names, data types and missing values
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Name    6 non-null      object
 2   Age     6 non-null      int64
 3   City    6 non-null      object
 4   Marks   6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

**Step 13: Display Statistical Summary**

In [ ]:
# Show statistical summary of numeric columns
df_csv.describe()

             ID        Age      Marks
count  6.000000   6.000000   6.000000
mean   3.500000  37.500000  77.500000
std    1.870829   9.354143   9.354143
min    1.000000  25.000000  65.000000
25%    2.250000  31.250000  71.250000
50%    3.500000  37.500000  77.500000
75%    4.750000  43.750000  83.750000
max    6.000000  50.000000  90.000000

**Step 14: Display Dataset Shape**

In [ ]:
# Display the number of rows and columns
df_csv.shape

(6, 5)

**Step 15: Display Column Names**

In [ ]:
# Display all column names
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step 16: Display Data Types**

In [ ]:
# Display the data type of each column
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step 17: Check for Missing Values**

In [ ]:
# Check for missing (NULL) values in each column

# isnull() checks whether a value is missing
# sum() counts the total missing values in each column
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step 18: Dispaly a Single Column**

In [ ]:
# Display only the City column
df_csv["City"]

0          Surat
1        Navsari
2         Valsad
3          Surat
4    Gandhinagar
5        Bharuch
Name: City, dtype: object

**Step 19: Display Multiple Columns**

In [ ]:
# Display only the Name and Marks columns
df_csv[["Name", "Marks"]]

    Name  Marks
0  Rahul     90
1  Priya     85
2   Amit     80
3  Karan     75
4   Riya     70
5   Aman     65

**Step 20: Filter Records**

In [ ]:
# Display students whose Marks are greater than 80
df_csv[df_csv["Marks"] > 80]

   ID   Name  Age     City  Marks
0   1  Rahul   25    Surat     90
1   2  Priya   30  Navsari     85

**Step 21: Calculate Average Marks**

In [ ]:
# Calculate the average of the Marks column
df_csv["Marks"].mean()

np.float64(77.5)

**Step 22: Sort Data**

In [ ]:
# Sort the DataFrame by Name in descending order

# by="Name" means sort using the Name column
# ascending=False means sort from Z to A
df_csv.sort_values(by="Name", ascending=False)

   ID   Name  Age         City  Marks
4   5   Riya   45  Gandhinagar     70
0   1  Rahul   25        Surat     90
1   2  Priya   30      Navsari     85
3   4  Karan   40        Surat     75
2   3   Amit   35       Valsad     80
5   6   Aman   50      Bharuch     65