**240840116011**

**Practical 3**

**Aim: Apply filtering, sorting, aggregation, and GroupBy operations on real-world datasets.**

In [1]:
# Import the Pandas library
# Pandas is used to work with data in table format
import pandas as pd

In [2]:
# Create a dictionary to store employee data
# Each key becomes a column name
# Each list contains the values of that column
data = {
    "Emp_ID":[101,102,103,104,105,106,107,108],
    "Name":['Rahul','Priya','Amit','Riya','Karan','Neha','Vivek','Pooja'],
    "Department":['IT','HR','IT','Finance','HR','Finance','IT','HR'],
    "City":['Surat','Navsari','Surat','Valsad','Surat','Navsari','Valsad','Surat'],
    "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience":[2,1,5,4,2,6,8,3]
}

In [3]:
# Create a DataFrame named df
# Convert the dictionary into a Pandas DataFrame
df = pd.DataFrame(data)

**Step 1: Display the Dataset**

In [4]:
# Display the dataset
df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step 2: Filter Data**

In [5]:
# Display employees working in the IT department
df[df['Department']=='IT']

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Display Employees with salary Greater than 50000

In [6]:
# Display employees whose salary is greater than 50000
df[df['Salary']>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

Display Employees from Surat

In [7]:
# Display employees who are from Surat
df[df['City']=='Surat']

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

Apply Multiple Conditions

In [8]:
# Display IT employees whose salary is greater than 50000
df[(df['Department']=='IT') & (df['Salary']>50000)]

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**Step 2: Sort Data**

Sort Salary in Ascending Order

In [9]:
# Sort employees by salary from lowest to highest
df.sort_values(by='Salary')

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

Sort Salary in Descending Order

In [10]:
# Sort employees by salary from highest to lowest
df.sort_values(by=['Salary'], ascending=[False])

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

Sort by Department and Salary

In [11]:
# Sort first by Department and then by Salary
df.sort_values(by=['Department','Salary'], ascending=[True,False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

**Step 4: Perform Aggregation**

Calculate Total Salary

In [12]:
# Calculate the total salary of all employees
df['Salary'].sum()

np.int64(376000)

Calculate Average salary

In [13]:
# Calculate the average salary
df['Salary'].mean()

np.float64(47000.0)

Find highest Salary

In [14]:
# Find the highest salary
df['Salary'].max()

60000

Find lowest Salary

In [15]:
# Find the lowest salary
df['Salary'].min()

38000

Count Employees

In [16]:
# Count the total number of employees
df['Emp_ID'].count()

np.int64(8)

**Step 5: Perform GroupBY Opertaions**

Average Salary Department-Wise

In [17]:
# Calculate average salary for each department
df.groupby('Department')['Salary'].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Minimum Salary Department-Wise

In [18]:
# Find minimum salary in each department
df.groupby('Department')['Salary'].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Count Total Employees Department-Wise

In [19]:
# Count employees in each department
df.groupby('Department')['Emp_ID'].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_ID, dtype: int64

Total Salary Department-Wise

In [20]:
# Calculate total salary for each department
df.groupby('Department')['Salary'].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

Maximum Salary Department-Wise

In [21]:
# Find the highest salary in each department
df.groupby('Department')['Salary'].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

Group by City

In [22]:
# City Wise Average Salary
df.groupby('City')['Salary'].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

**Step 6: Multiple Aggregation Function**

In [23]:
# Perform multiple calculations on salary department-wise
df.groupby('Department')['Salary'].agg(['count','sum','mean','min','max'])

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

**Step 7: Save the Result to CSV File and Download CSV File**

In [24]:
# Save the DataFrame as a CSV file
df.to_csv('Employee_Data.csv', index=False)

# Import Google Colab file handling
from google.colab import files

# Download the CSV file
files.download('Employee_Data.csv')